# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2048M

# Mod properties
mod_version=1.4.41
maven_group=net.satisfy
archives_base_name=vinery
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.1

# Dependencies
architectury_version=13.0.8
rei_version=16.0.799
jei_version=19.25.0.321
cloth_fabric_version=15.0.140
mod_menu_version=11.0.3
fabric_loader_version=0.16.10
fabric_api_version=0.103.0+1.21.1
neo_forge_version=21.1.209
