package satisfyu.vinery.item;

import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import satisfyu.vinery.Vinery;
import satisfyu.vinery.registry.ObjectRegistry;

public class VineryTabs {
    public static final DeferredRegister<CreativeModeTab> VINERY_TABS = DeferredRegister.create(Vinery.MODID, Registries.CREATIVE_MODE_TAB);

    public static final RegistrySupplier<CreativeModeTab> VINERY_TAB = VINERY_TABS.register("vinery", () -> CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0)
            .icon(() -> new ItemStack(ObjectRegistry.JUNGLE_RED_GRAPE.get()))
            .title(Component.translatable("creativetab.vinery.tab"))
            .displayItems((parameters, output) -> {
                output.accept(ObjectRegistry.CHERRY.get());
                output.accept(ObjectRegistry.ROTTEN_CHERRY.get());
                output.accept(ObjectRegistry.RED_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.RED_GRAPE.get());
                output.accept(ObjectRegistry.WHITE_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.WHITE_GRAPE.get());
                output.accept(ObjectRegistry.SAVANNA_RED_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.SAVANNA_RED_GRAPE.get());
                output.accept(ObjectRegistry.SAVANNA_WHITE_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.SAVANNA_WHITE_GRAPE.get());
                output.accept(ObjectRegistry.TAIGA_RED_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.TAIGA_RED_GRAPE.get());
                output.accept(ObjectRegistry.TAIGA_WHITE_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.TAIGA_WHITE_GRAPE.get());
                output.accept(ObjectRegistry.JUNGLE_RED_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.JUNGLE_RED_GRAPE.get());
                output.accept(ObjectRegistry.JUNGLE_WHITE_GRAPE_SEEDS.get());
                output.accept(ObjectRegistry.JUNGLE_WHITE_GRAPE.get());
                output.accept(ObjectRegistry.CHERRY_SAPLING.get());
                output.accept(ObjectRegistry.APPLE_TREE_SAPLING.get());
                output.accept(ObjectRegistry.GRAPEVINE_LEAVES.get());
                output.accept(ObjectRegistry.CHERRY_LEAVES.get());
                output.accept(ObjectRegistry.APPLE_LEAVES.get());
                output.accept(ObjectRegistry.WHITE_GRAPE_CRATE.get());
                output.accept(ObjectRegistry.RED_GRAPE_CRATE.get());
                output.accept(ObjectRegistry.CHERRY_CRATE.get());
                output.accept(ObjectRegistry.APPLE_CRATE.get());
                output.accept(ObjectRegistry.GRAPEVINE_POT.get());
                output.accept(ObjectRegistry.FERMENTATION_BARREL.get());
                output.accept(ObjectRegistry.WINE_PRESS.get());
                output.accept(ObjectRegistry.CHAIR.get());
                output.accept(ObjectRegistry.TABLE.get());
                output.accept(ObjectRegistry.WINE_RACK_1.get());
                output.accept(ObjectRegistry.WINE_RACK_2.get());
                output.accept(ObjectRegistry.WINE_RACK_3.get());
                output.accept(ObjectRegistry.WINE_RACK_5.get());
                output.accept(ObjectRegistry.BARREL.get());
                output.accept(ObjectRegistry.STRIPPED_CHERRY_LOG.get());
                output.accept(ObjectRegistry.CHERRY_LOG.get());
                output.accept(ObjectRegistry.STRIPPED_CHERRY_WOOD.get());
                output.accept(ObjectRegistry.CHERRY_WOOD.get());
                output.accept(ObjectRegistry.APPLE_LOG.get());
                output.accept(ObjectRegistry.APPLE_WOOD.get());
                output.accept(ObjectRegistry.CHERRY_BEAM.get());
                output.accept(ObjectRegistry.CHERRY_PLANKS.get());
                output.accept(ObjectRegistry.CHERRY_FLOORBOARD.get());
                output.accept(ObjectRegistry.CHERRY_STAIRS.get());
                output.accept(ObjectRegistry.CHERRY_SLAB.get());
                output.accept(ObjectRegistry.CHERRY_FENCE.get());
                output.accept(ObjectRegistry.CHERRY_FENCE_GATE.get());
                output.accept(ObjectRegistry.CHERRY_BUTTON.get());
                output.accept(ObjectRegistry.CHERRY_PRESSURE_PLATE.get());
                output.accept(ObjectRegistry.CHERRY_DOOR.get());
                output.accept(ObjectRegistry.CHERRY_TRAPDOOR.get());
                output.accept(ObjectRegistry.CHERRY_SIGN_ITEM.get());
                output.accept(ObjectRegistry.WINDOW.get());
                output.accept(ObjectRegistry.GRAPEVINE_LATTICE.get());
                output.accept(ObjectRegistry.LOAM.get());
                output.accept(ObjectRegistry.LOAM_STAIRS.get());
                output.accept(ObjectRegistry.LOAM_SLAB.get());
                output.accept(ObjectRegistry.COARSE_DIRT_SLAB.get());
                output.accept(ObjectRegistry.DIRT_SLAB.get());
                output.accept(ObjectRegistry.GRASS_SLAB.get());
                output.accept(ObjectRegistry.APPLE_JUICE.get());
                output.accept(ObjectRegistry.RED_GRAPEJUICE_WINE_BOTTLE.get());
                output.accept(ObjectRegistry.WHITE_GRAPEJUICE_WINE_BOTTLE.get());
                output.accept(ObjectRegistry.TAIGA_RED_GRAPEJUICE_BOTTLE.get());
                output.accept(ObjectRegistry.TAIGA_WHITE_GRAPEJUICE_BOTTLE.get());
                output.accept(ObjectRegistry.JUNGLE_RED_GRAPEJUICE_BOTTLE.get());
                output.accept(ObjectRegistry.JUNGLE_WHITE_GRAPEJUICE_BOTTLE.get());
                output.accept(ObjectRegistry.SAVANNA_RED_GRAPEJUICE_BOTTLE.get());
                output.accept(ObjectRegistry.SAVANNA_WHITE_GRAPEJUICE_BOTTLE.get());
                output.accept(ObjectRegistry.CHORUS_WINE.get());
                output.accept(ObjectRegistry.CHERRY_WINE.get());
                output.accept(ObjectRegistry.MAGNETIC_WINE.get());
                output.accept(ObjectRegistry.NOIR_WINE.get());
                output.accept(ObjectRegistry.KING_DANIS_WINE.get());
                output.accept(ObjectRegistry.MELLOHI_WINE.get());
                output.accept(ObjectRegistry.STAL_WINE.get());
                output.accept(ObjectRegistry.STRAD_WINE.get());
                output.accept(ObjectRegistry.SOLARIS_WINE.get());
                output.accept(ObjectRegistry.BOLVAR_WINE.get());
                output.accept(ObjectRegistry.AEGIS_WINE.get());
                output.accept(ObjectRegistry.CLARK_WINE.get());
                output.accept(ObjectRegistry.CHENET_WINE.get());
                output.accept(ObjectRegistry.KELP_CIDER.get());
                output.accept(ObjectRegistry.APPLE_WINE.get());
                output.accept(ObjectRegistry.APPLE_CIDER.get());
                output.accept(ObjectRegistry.JELLIE_WINE.get());
                output.accept(ObjectRegistry.RED_WINE.get());
                output.accept(ObjectRegistry.PRAETORIAN_WINE.get());
                output.accept(ObjectRegistry.JO_SPECIAL_MIXTURE.get());
                output.accept(ObjectRegistry.CRISTEL_WINE.get());
                output.accept(ObjectRegistry.CREEPERS_CRUSH.get());
                output.accept(ObjectRegistry.VILLAGERS_FRIGHT.get());
                output.accept(ObjectRegistry.GLOWING_WINE.get());
                output.accept(ObjectRegistry.MEAD.get());
                output.accept(ObjectRegistry.BOTTLE_MOJANG_NOIR.get());
                output.accept(ObjectRegistry.EISWEIN.get());
                output.accept(ObjectRegistry.WINE_BOTTLE.get());
                output.accept(ObjectRegistry.APPLE_MASH.get());
                output.accept(ObjectRegistry.GRAPEVINE_STEM.get());
                output.accept(ObjectRegistry.STORAGE_POT.get());
                output.accept(ObjectRegistry.FLOWER_BOX.get());
                output.accept(ObjectRegistry.FLOWER_POT.get());
                output.accept(ObjectRegistry.WINE_BOX.get());
                output.accept(ObjectRegistry.SHELF.get());
                output.accept(ObjectRegistry.BIG_TABLE.get());
                output.accept(ObjectRegistry.BASKET.get());
                output.accept(ObjectRegistry.STACKABLE_LOG.get());
                output.accept(ObjectRegistry.STRAW_HAT.get());
                output.accept(ObjectRegistry.VINEMAKER_APRON.get());
                output.accept(ObjectRegistry.VINEMAKER_LEGGINGS.get());
                output.accept(ObjectRegistry.VINEMAKER_BOOTS.get());
                output.accept(ObjectRegistry.GLOVES.get());
                output.accept(ObjectRegistry.MULE_SPAWN_EGG.get());
                output.accept(ObjectRegistry.WANDERING_WINEMAKER_SPAWN_EGG.get());
                output.accept(ObjectRegistry.OAK_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.OAK_WINE_RACK_BIG.get());
                output.accept(ObjectRegistry.SPRUCE_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.SPRUCE_WINE_RACK_BIG.get());
                output.accept(ObjectRegistry.BIRCH_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.BIRCH_WINE_RACK_BIG.get());
                output.accept(ObjectRegistry.JUNGLE_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.JUNGLE_WINE_RACK_BIG.get());
                output.accept(ObjectRegistry.ACACIA_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.ACACIA_WINE_RACK_BIG.get());
                output.accept(ObjectRegistry.DARK_OAK_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.DARK_OAK_WINE_RACK_BIG.get());
                output.accept(ObjectRegistry.MANGROVE_WINE_RACK_SMALL.get());
                output.accept(ObjectRegistry.MANGROVE_WINE_RACK_BIG.get());
            })
            .build());

    public static void init() {
        VINERY_TABS.register();
    }
}
