plugins {
    id "com.github.johnrengelman.shadow"
    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}


def jarFileName = 'letsdo-vinery-neoforge'
def changelogText = rootProject.file("CHANGELOG.md").text
archivesBaseName = jarFileName


loom {
    accessWidenerPath.set(project(":common").loom.accessWidenerPath)
    runs {
        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
    }
}

repositories {
    maven { url 'https://jitpack.io' }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:${neo_forge_version}"
    modApi "dev.architectury:architectury-neoforge:${architectury_version}"

    modImplementation "me.shedaniel:RoughlyEnoughItems-neoforge:$rei_version"
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle project(path: ":common", configuration: "transformProductionNeoForge")
    //modLocalRuntime "com.github.jab125.architectury-data-generation-fix:architectury-data-generation-fix-neoforge:21.0.0"

}



processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    publications {
        mavenForge(MavenPublication) {
            artifactId = rootProject.archives_base_name + "-" + project.name
            from components.java
        }
    }

    repositories {
    }
}

//modrinth {
//    token = System.getenv("MODRINTH_TOKEN")
//    projectId = "lets-do-vinery"
//    versionNumber = rootProject.mod_version
//    versionName = "${rootProject.archives_base_name}-${rootProject.mod_version} [${rootProject.minecraft_version}-neoforge]"
//    versionType = "release"
//    changelog = rootProject.file("CHANGELOG.md").exists() ? rootProject.file("CHANGELOG.md").text : " "
//    gameVersions = [rootProject.minecraft_version]
//    loaders = ["neoforge"]
//    uploadFile = remapJar
//    additionalFiles = [tasks.sourcesJar.archiveFile]
//
//    dependencies {
//        required.project "architectury-api"
//    }
//}
//
//curseforge {
//    apiKey = System.getenv("CURSEFORGE_API_KEY")
//    project {
//        id = "704465"
//        releaseType = "release"
//        addGameVersion rootProject.minecraft_version
//        addGameVersion "Forge"
//        mainArtifact(remapJar) {
//            displayName = "Vinery - ${rootProject.mod_version} - FORGE - ${rootProject.minecraft_version}"
//            changelog = changelogText
//            changelogType = "markdown"
//        }
//
//        relations {
//            requiredDependency "architectury-api"
//        }
//    }
